name: avd_manager
description: "An app to manage Android Virtual Devices"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  process_run: ^0.13.2
  hooks_riverpod: ^2.4.8
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  window_manager: ^0.3.7
  flutter_hooks: ^0.20.3
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
